*** Exception: foo
Stopped at <exception thrown>
_exception :: e = _
Stopped at <exception thrown>
_exception :: e = _
-1  : main (..\Test7.hs:2:17-27)
-2  : main (..\Test7.hs:2:7-28)
<end of history>
Logged breakpoint at ..\Test7.hs:2:17-27
_result :: a
Logged breakpoint at ..\Test7.hs:2:7-28
_result :: IO a
no more logged breakpoints
Logged breakpoint at ..\Test7.hs:2:17-27
_result :: a
Stopped at <exception thrown>
_exception :: e
already at the beginning of the history
_exception = SomeException (GHC.Exception.D:Exception _
                                                      (GHC.Show.D:Show _ _ _) _ _)
                           (ErrorCall ['f','o','o'])
_exception ::
  SomeException = SomeException (GHC.Exception.D:Exception _
                                                           (GHC.Show.D:Show ...) ....)
                                (ErrorCall ['f',....])
_result :: a = _
*** Exception: foo
*** Exception: foo
